name: Deploy FifaWorldCupQatar2022

on:
  push:
    branches: [ main ]
  schedule:
  - cron: '0 18 * * 0-6'

  repository_dispatch:
    types: [WorldCupQatar2022]
  
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
  

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRETS}}

    - name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: nosaugowe/restfulapi-qatar2022